name: Deploy Infrastructure (IaC)

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy-infra:
    runs-on: ubuntu-latest  # The GitHub runner environment

    steps:
      - name: 🚀 Checkout Code
        uses: actions/checkout@v3  # Check out the repository

      - name: 🔑 Azure Login
        uses: azure/login@v1  # Authenticate to Azure using the secret
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Reference the secret we created

      - name: 📦 Deploy Virtual Network (vnet.bicep)
        run: |
          az deployment group create \
            --resource-group rg-calicot-dev \
            --template-file COFOMOBicepFiles/vnet.bicep \
            --parameters location="Canada Central"  # Use the location parameter

      - name: 📦 Deploy Application Network (app.net.bicep)
        run: |
          az deployment group create \
            --resource-group rg-calicot-dev \
            --template-file COFOMOBicepFiles/app.net.bicep \
            --parameters location="Canada Central"  # Use the location parameter

      - name: 📦 Deploy Key Vault (keyvault.net.bicep)
        run: |
          az deployment group create \
            --resource-group rg-calicot-dev \
            --template-file COFOMOBicepFiles/keyvault.net.bicep \
            --parameters location="Canada Central"  # Use the location parameter
